comments:
  active: true
  UndocumentedPublicClass:
    active: true
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/commonTest/**"
      - "**/jvmTest/**"
      - "**/jsTest/**"
      - "**/iosTest/**"
      - "**/com/patrykandpatrick/vico/sample/**"
    ignoreAnnotated:
      - "RestrictTo"
  UndocumentedPublicFunction:
    active: true
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/commonTest/**"
      - "**/jvmTest/**"
      - "**/jsTest/**"
      - "**/iosTest/**"
      - "**/com/patrykandpatrick/vico/sample/**"
    ignoreAnnotated:
      - "RestrictTo"
  UndocumentedPublicProperty:
    active: true
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/commonTest/**"
      - "**/jvmTest/**"
      - "**/jsTest/**"
      - "**/iosTest/**"
      - "**/com/patrykandpatrick/vico/sample/**"
    ignoreAnnotated:
      - "RestrictTo"
complexity:
  active: false
style:
  MagicNumber:
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/commonTest/**"
      - "**/jvmTest/**"
      - "**/jsTest/**"
      - "**/iosTest/**"
      - "**/previews/**"
      - "**/Preview.kt"
      - "**/Previews.kt"
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
      - "100"
  UnnecessaryParentheses:
    active: true
    allowForUnclearPrecedence: true
naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
formatting:
  active: true
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
