name: Release update
on:
  workflow_dispatch:
jobs:
  release_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: vico
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          distribution: adopt
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: |
          git config --global user.email "96002241+patrykandpatrykbot@users.noreply.github.com"
          git config --global user.name "Vico Chart Bot"
          pip install --upgrade pip
          pip install mkdocs mkdocs-material
          git clone https://github.com/patrykandpatryk/patrykandpatryk.com
          cd ${{ github.workspace }}/vico
          chmod +x gradlew
          OLD_VERSION_NAME=$(grep -oP "(?<=com\.patrykandpatryk\.vico:view:).*(?=\")" README.md)
          NEW_VERSION_NAME=$(grep -oP "(?<=version_name).*(?=\",)" versions.gradle | grep -oP "(?<=\").*")
          echo "OLD_VERSION_NAME=$OLD_VERSION_NAME" >> $GITHUB_ENV
          echo "NEW_VERSION_NAME=$NEW_VERSION_NAME" >> $GITHUB_ENV
          sed -i "s/$OLD_VERSION_NAME/$NEW_VERSION_NAME/g" README.md
          git add README.md
          git commit -m "Update README"
          echo "TAG_NAME=v$NEW_VERSION_NAME" >> $GITHUB_ENV
          IS_PRERELEASE=false
          echo $NEW_VERSION_NAME | grep -q "alpha\|beta" && IS_PRERELEASE=true
          echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          token: ${{ secrets.VICO_CHART_BOT_PAT }}
          body_path: ${{ github.workspace }}/vico/CHANGELOG.md
          prerelease: ${{ env.IS_PRERELEASE }}
      - run: |
          cd ${{ github.workspace }}/vico
          true > "CHANGELOG.md"
          git add CHANGELOG.md
          git commit -m "Empty \`CHANGELOG.md\`"
          git remote set-url origin https://patrykandpatrykbot:${{ secrets.VICO_CHART_BOT_PAT }}@github.com/patrykandpatryk/vico.git
          ./gradlew dokkaHtmlMultiModule
          cd wiki
          mkdocs build
          rm -r ${{ github.workspace }}/patrykandpatryk.com/vico/api/*
          rm -r ${{ github.workspace }}/patrykandpatryk.com/vico/wiki/*
          cp -R ${{ github.workspace }}/vico/docs/. ${{ github.workspace }}/patrykandpatryk.com/vico/api
          cp -R ${{ github.workspace }}/vico/wiki/site/. ${{ github.workspace }}/patrykandpatryk.com/vico/wiki
          cd ${{ github.workspace }}/patrykandpatryk.com
          git remote set-url origin https://patrykandpatrykbot:${{ secrets.VICO_CHART_BOT_PAT }}@github.com/patrykandpatryk/patrykandpatryk.com.git
          git add vico/api
          git commit -m "Update Vico API reference"
          git add vico/wiki
          git diff-index --quiet HEAD || git commit -m "Update Vico wiki"
          git push origin
          cd ${{ github.workspace }}/vico
          git push origin
          ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_vicoSigningKey: ${{ secrets.VICO_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_vicoSigningPassword: ${{ secrets.VICO_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_vicoUserName: ${{ secrets.VICO_USER_NAME }}
          ORG_GRADLE_PROJECT_vicoUserPassword: ${{ secrets.VICO_USER_PASSWORD }}
