name: Update wiki
on:
  workflow_dispatch:
jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/patrykandpatryk/vico
          git clone https://github.com/patrykandpatryk/patrykandpatryk.com
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: adopt
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: |
          git config --global user.email "96002241+patrykandpatrykbot@users.noreply.github.com"
          git config --global user.name "Patryk & Patryk Bot"
          pip install --upgrade pip
          pip install mkdocs mkdocs-material
          cd ${{ github.workspace }}/vico
          git checkout ${GITHUB_REF##*/}
          cd wiki
          mkdocs build
          cp -a ${{ github.workspace }}/vico/wiki/site/. ${{ github.workspace }}/patrykandpatryk.com/vico/wiki
          cd ${{ github.workspace }}/patrykandpatryk.com
          git remote set-url origin https://patrykandpatrykbot:${{ secrets.VICO_CHART_BOT_PAT }}@github.com/patrykandpatryk/patrykandpatryk.com.git
          git add vico/wiki
          git commit -m "Update Vico wiki"
          git push origin
